require("options")
require("keymaps")

require("plugins.setup")
require("plugins.cfg-lualine")
require("plugins.cfg-nvim-tree")
require("plugins.cfg-treesitter")
require("plugins.cfg-lsp")
require("plugins.cfg-cmp")
require("plugins.cfg-comments")
require("plugins.cfg-autopairs")
require("plugins.cfg-bufferline")
require("plugins.cfg-gitsigns")
require("plugins.cfg-telescope")
require("plugins.cfg-which-key")
require("plugins.cfg-github-copilot")
